language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
  -
  - REDISTOGO_URL='redis://dummy'
  - OPENREDIS_URL='redis://dummy'
  - REDISTOGO_URL='redis://dummy1' OPENREDIS_URL='redis://dummy2'
install:
  - pip install nose
  - pip install .
script: nosetests -q tests
